color0 #3f484a
color1 #ffb4ab
color2 #82d3e2
color3 #b1cbd0
color4 #bbc5ea
color5 #82d3e2
color6 #b1cbd0
color7 #dee3e5
color8 #899294
color9 #ffb4ab
color10 #82d3e2
color11 #b1cbd0
color12 #bbc5ea
color13 #82d3e2
color14 #b1cbd0
color15 #dee3e5

cursor                #dee3e5
cursor_text_color     #000000
background            #000000
foreground            #dee3e5
selection_foreground  #bfc8ca
selection_background  #3f484a
active_border_color   #82d3e2
inactive_border_color #323b3d
url_color             #82d3e2

active_tab_foreground   #00363e
active_tab_background   #82d3e2
inactive_tab_foreground #bfc8ca
inactive_tab_background #323b3d
cursor_trail_color      #bfc8ca
